
import { Dish, Table, Order } from './types';

export const MENU_CATEGORIES = [
  'Tutti',
  'Antipasti',
  'Sushi & Sashimi',
  'Uramaki',
  'Temaki',
  'Ramen',
  'Donburi',
  'Piatti Caldi',
  'Dessert',
  'Bevande',
];

export const MOCK_DISHES: Dish[] = [
  // --- NUOVA SEZIONE ANTIPASTI ---
  {
    _id: 'dish-1',
    name: 'Involtini Primavera',
    category: 'Antipasti',
    description: 'Croccanti involtini di verdure fresche, serviti con salsa agrodolce.',
    price: 5.0,
    imageUrl: 'https://i.imgur.com/igHsfiH.jpeg',
    available: true,
    ingredients: ['Carote', 'Cavolo', 'Cipolle', 'Germogli di soia'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['Vegan', 'Halal', 'Kosher'],
    allergens: ['Glutine', 'Soia'],
  },
  {
    _id: 'dish-2',
    name: 'Involtini di Gamberi',
    category: 'Antipasti',
    description: 'Involtini fritti dorati ripieni di gamberi, serviti in un\'elegante ciotola di ceramica.',
    price: 6.5,
    imageUrl: 'https://i.imgur.com/T1R1Gn8.jpeg',
    available: true,
    ingredients: ['Gamberi', 'Pasta per involtini'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['Halal', 'Kosher'],
    allergens: ['Glutine', 'Crostacei'],
  },
   {
    _id: 'dish-8',
    name: 'Ravioli al Vapore',
    category: 'Antipasti',
    description: 'Ravioli tradizionali con ripieno di carne e verdure, serviti nel classico cestello di bamboo.',
    price: 6.0,
    imageUrl: 'https://i.imgur.com/hDAXAcs.jpeg',
    available: true,
    ingredients: ['Maiale', 'Cavolo', 'Cipollotto'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['Kosher'],
    allergens: ['Glutine', 'Soia'],
  },
  {
    _id: 'dish-9',
    name: 'Shaomai di Gamberi',
    category: 'Antipasti',
    description: 'Ravioli aperti al vapore con un gustoso ripieno di carne e gamberi, guarniti con uova di pesce.',
    price: 7.0,
    imageUrl: 'https://i.imgur.com/EZfGPKX.jpeg',
    available: true,
    ingredients: ['Gamberi', 'Maiale', 'Uova di pesce'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['None'],
    allergens: ['Glutine', 'Crostacei', 'Pesce', 'Soia'],
  },
  {
    _id: 'dish-10',
    name: 'Edamame',
    category: 'Antipasti',
    description: 'Fagioli di soia al vapore con sale marino, serviti in una ciotola scura minimalista.',
    price: 4.5,
    imageUrl: 'https://i.imgur.com/Gsgijon.jpeg',
    available: true,
    ingredients: ['Edamame', 'Sale'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['Vegan', 'Halal', 'Kosher'],
    allergens: ['Soia'],
  },
  {
    _id: 'dish-11',
    name: 'Pane Cinese al Vapore',
    category: 'Antipasti',
    description: 'Panini cinesi bianchi e morbidi, serviti caldi con un leggero fumo di vapore.',
    price: 4.0,
    imageUrl: 'https://i.imgur.com/5vSLpsV.jpeg',
    available: true,
    ingredients: ['Farina', 'Lievito', 'Zucchero'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['Halal', 'Kosher'],
    allergens: ['Glutine'],
  },
   {
    _id: 'dish-12',
    name: 'Nuvole di Drago',
    category: 'Antipasti',
    description: 'Le classiche chips di gambero asiatiche, croccanti e leggere, servite in un cestino di bambù.',
    price: 3.5,
    imageUrl: 'https://i.imgur.com/QQPYb4V.jpeg',
    available: true,
    ingredients: ['Amido di tapioca', 'Gamberi'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['Halal', 'Kosher'],
    allergens: ['Crostacei'],
  },
  {
    _id: 'dish-13',
    name: 'Insalata di Alghe Wakame',
    category: 'Antipasti',
    description: 'Fresca insalata di alghe wakame condita con semi di sesamo, servita con bacchette.',
    price: 5.5,
    imageUrl: 'https://i.imgur.com/Pejj0Wt.jpeg',
    available: true,
    ingredients: ['Alghe Wakame', 'Sesamo', 'Aceto di riso'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['Vegan', 'Halal', 'Kosher'],
    allergens: ['Sesamo'],
  },
  // --- FINE SEZIONE ANTIPASTI ---
  {
    _id: 'dish-3',
    name: 'Sashimi Misto',
    category: 'Sushi & Sashimi',
    description: 'Selezione di pesce crudo fresco: salmone, tonno e branzino.',
    price: 18.0,
    imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?q=80&w=800&auto=format&fit=crop',
    available: true,
    ingredients: ['Salmone', 'Tonno', 'Branzino'],
    type: ['Asporto'],
    religionTags: ['Halal', 'Kosher'],
    allergens: ['Pesce'],
  },
  {
    _id: 'dish-4',
    name: 'Spicy Tuna Uramaki',
    category: 'Uramaki',
    description: 'Rotolo di riso con tonno piccante, cetriolo e avocado, guarnito con sesamo.',
    price: 12.0,
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=800&auto=format&fit=crop',
    available: true,
    ingredients: ['Riso', 'Tonno', 'Salsa piccante', 'Cetriolo', 'Avocado', 'Sesamo'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['Halal'],
    allergens: ['Pesce', 'Sesamo', 'Soia'],
  },
  {
    _id: 'dish-5',
    name: 'Tonkotsu Ramen',
    category: 'Ramen',
    description: 'Brodo di maiale ricco e cremoso, con fettine di maiale, uovo marinato e naruto.',
    price: 15.0,
    imageUrl: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?q=80&w=800&auto=format&fit=crop',
    available: false,
    ingredients: ['Noodles', 'Brodo di maiale', 'Maiale Chashu', 'Uovo', 'Naruto', 'Cipollotto'],
    type: ['All You Can Eat'],
    religionTags: ['None'],
    allergens: ['Glutine', 'Uova', 'Soia'],
  },
  {
    _id: 'dish-6',
    name: 'Chicken Katsu Don',
    category: 'Donburi',
    description: 'Ciotola di riso con cotoletta di pollo fritta, uovo e cipolle.',
    price: 13.0,
    imageUrl: 'https://images.unsplash.com/photo-1582650859342-3a53994503f1?q=80&w=800&auto=format&fit=crop',
    available: true,
    ingredients: ['Riso', 'Pollo', 'Uovo', 'Cipolla', 'Salsa Donburi'],
    type: ['All You Can Eat', 'Asporto'],
    religionTags: ['None'],
    allergens: ['Glutine', 'Uova', 'Soia'],
  },
   {
    _id: 'dish-7',
    name: 'Mochi Gelato',
    category: 'Dessert',
    description: 'Dolcetti di riso glutinoso ripieni di gelato. Gusti assortiti.',
    price: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1625943555499-591255c28f3c?q=80&w=800&auto=format&fit=crop',
    available: true,
    ingredients: ['Riso glutinoso', 'Zucchero', 'Gelato'],
    type: ['All You Can Eat'],
    religionTags: ['Vegan', 'Halal', 'Kosher'],
    allergens: ['Latte (a seconda del gusto)'],
  },
];


const MOCK_ORDER_1: Order = {
    _id: 'order-1',
    tableId: 't1',
    items: [
        { dish: MOCK_DISHES[3], quantity: 2, status: 'servito' },
        { dish: MOCK_DISHES[1], quantity: 1, status: 'pronto' },
        { dish: MOCK_DISHES[6], quantity: 1, status: 'in preparazione' },
    ],
    total: MOCK_DISHES[3].price * 2 + MOCK_DISHES[1].price + MOCK_DISHES[6].price,
    status: 'active',
    createdAt: new Date('2023-10-27T19:45:00Z').toISOString(),
    updatedAt: new Date('2023-10-27T20:15:00Z').toISOString(),
};

const MOCK_ORDER_2: Order = {
    _id: 'order-2',
    tableId: 't3',
    items: [
        { dish: MOCK_DISHES[4], quantity: 1, status: 'in preparazione' },
        { dish: MOCK_DISHES[0], quantity: 1, status: 'in preparazione' },
    ],
    total: MOCK_DISHES[4].price + MOCK_DISHES[0].price,
    status: 'active',
    createdAt: new Date('2023-10-27T20:00:00Z').toISOString(),
    updatedAt: new Date('2023-10-27T20:10:00Z').toISOString(),
};

const MOCK_PAST_ORDER: Order = {
    _id: 'order-past-1',
    tableId: 't1',
    items: [{ dish: MOCK_DISHES[2], quantity: 2, status: 'servito' }],
    total: MOCK_DISHES[2].price * 2,
    status: 'completed',
    createdAt: new Date('2023-10-26T20:00:00Z').toISOString(),
    updatedAt: new Date('2023-10-26T21:00:00Z').toISOString(),
}

export const MOCK_TABLES: Table[] = [
    { _id: 't1', name: 'Tavolo 1', status: 'Occupato', activeOrder: MOCK_ORDER_1, orderHistory: [MOCK_PAST_ORDER], position: {x: 50, y: 50} },
    { _id: 't2', name: 'Tavolo 2', status: 'Libero', activeOrder: null, orderHistory: [], position: {x: 200, y: 50} },
    { _id: 't3', name: 'Tavolo 3', status: 'Ordinazione Inviata', activeOrder: MOCK_ORDER_2, orderHistory: [], position: {x: 350, y: 50} },
    { _id: 't4', name: 'Tavolo 4', status: 'Libero', activeOrder: null, orderHistory: [], position: {x: 50, y: 200} },
    { _id: 't5', name: 'Tavolo 5', status: 'Conto richiesto', activeOrder: MOCK_ORDER_1, orderHistory: [], position: {x: 200, y: 200} },
    { _id: 't6', name: 'Tavolo 6', status: 'Libero', activeOrder: null, orderHistory: [], position: {x: 350, y: 200} },
];
